/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2025-03-04 07:33:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/eGovFrameDev-3.10.0-git/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/eGovTest/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612850416000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Board Detail</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1 class=\"text-center\">Board Detail</h1>\r\n");
      out.write("        <form action=\"updateMain.do\" id=\"viewForm\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <table class=\"table table-bordered\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <!-- 글번호 -->\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>글번호</th>\r\n");
      out.write("                        <td><input name=\"testId\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.testId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\" readonly /></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 제목 -->\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>제목</th>\r\n");
      out.write("                        <td><input type=\"text\" name=\"testTitle\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.testTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\" /></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 내용 -->\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>내용</th>\r\n");
      out.write("                        <td><textarea name=\"testContent\" class=\"form-control\" style=\"height: 200px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.testContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 다운로드 -->\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 첨부파일 -->\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>첨부파일</th>\r\n");
      out.write("                        <td><input type=\"file\" name=\"uploadFile\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 버튼 -->\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"2\" class=\"text-end\">\r\n");
      out.write("                            <button id=\"btn_previous\" type=\"button\" class=\"btn btn-outline-secondary\">이전</button>\r\n");
      out.write("                            <button id=\"btn_modify\" type=\"button\" class=\"btn btn-primary\">수정</button>\r\n");
      out.write("                            <button id=\"btn_delete\" type=\"button\" class=\"btn btn-danger\">삭제</button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("        <!-- 댓글 영역 -->\r\n");
      out.write("\t\t<div class=\"comment-section mt-5\">\r\n");
      out.write("\t\t    <h3>댓글</h3>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <!-- 댓글 목록 -->\r\n");
      out.write("\t\t    <div id=\"commentList\" class=\"mb-4\">\r\n");
      out.write("\t\t        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <!-- 댓글 입력 폼 -->\r\n");
      out.write("\t\t    <div class=\"comment-form\">\r\n");
      out.write("\t\t        <form id=\"commentForm\">\r\n");
      out.write("\t\t            <input type=\"hidden\" name=\"testId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.testId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t            <div class=\"form-group mb-2\">\r\n");
      out.write("\t\t                <label for=\"commentName\">작성자</label>\r\n");
      out.write("\t\t                <input type=\"text\" class=\"form-control\" id=\"commentName\" name=\"commentName\" required>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            <div class=\"form-group mb-2\">\r\n");
      out.write("\t\t                <label for=\"commentContent\">내용</label>\r\n");
      out.write("\t\t                <textarea class=\"form-control\" id=\"commentContent\" name=\"commentContent\" rows=\"3\" required></textarea>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            <button type=\"button\" id=\"btn_comment_submit\" class=\"btn btn-primary float-end\">댓글 등록</button>\r\n");
      out.write("\t\t        </form>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        // 수정 버튼 클릭 이벤트\r\n");
      out.write("        $('#btn_modify').on('click', function () {\r\n");
      out.write("            if (confirm(\"정말 수정하시겠습니까?\")) {\r\n");
      out.write("                var formData = new FormData($('#viewForm')[0]);\r\n");
      out.write("                \r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    type: \"POST\",\r\n");
      out.write("                    url: \"updateMain.do\",\r\n");
      out.write("                    data: formData,\r\n");
      out.write("                    processData: false,\r\n");
      out.write("                    contentType: false,\r\n");
      out.write("                    success: function(response) {\r\n");
      out.write("                        document.open();\r\n");
      out.write("                        document.write(response);\r\n");
      out.write("                        document.close();\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function(error) {\r\n");
      out.write("                        console.error(\"Error:\", error);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 삭제 버튼 클릭 이벤트\r\n");
      out.write("        $('#btn_delete').on('click', function () {\r\n");
      out.write("            const testId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.testId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("            if (confirm(\"정말 삭제하시겠습니까?\")) {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    type: \"POST\",\r\n");
      out.write("                    url: \"deleteMain.do\",\r\n");
      out.write("                    data: { testId: testId },\r\n");
      out.write("                    success: function(response) {\r\n");
      out.write("                        document.open();\r\n");
      out.write("                        document.write(response);\r\n");
      out.write("                        document.close();\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function(error) {\r\n");
      out.write("                        console.error(\"Error:\", error);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 이전 버튼 클릭 이벤트\r\n");
      out.write("        $('#btn_previous').on('click', function () {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                url: \"main.do\",\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                    document.open();\r\n");
      out.write("                    document.write(response);\r\n");
      out.write("                    document.close();\r\n");
      out.write("                },\r\n");
      out.write("                error: function(error) {\r\n");
      out.write("                    console.error(\"Error:\", error);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("\t\t// 파일 삭제 버튼 클릭 이벤트\r\n");
      out.write("\t\t$('#filedelete').on('click', function () {\r\n");
      out.write("\t\t    const fileName = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; // 현재 첨부된 파일 이름\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    if (confirm(\"정말로 이 파일을 삭제하시겠습니까?\")) {\r\n");
      out.write("\t\t        $.ajax({\r\n");
      out.write("\t\t            type: \"POST\",\r\n");
      out.write("\t\t            url: \"deleteFile.do\", // 파일 삭제를 처리할 서버 엔드포인트\r\n");
      out.write("\t\t            data: { fileName: fileName }, // 서버로 전송할 데이터\r\n");
      out.write("\t\t            success: function (response) {\r\n");
      out.write("\t\t                if (response === 'success') {\r\n");
      out.write("\t\t                    alert(\"파일이 성공적으로 삭제되었습니다.\");\r\n");
      out.write("\t\t                    $('#filedelete').closest('tr').remove(); // 첨부파일 행 제거\r\n");
      out.write("\t\t                } else {\r\n");
      out.write("\t\t                    alert(\"파일 삭제에 실패했습니다.\");\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t            error: function (error) {\r\n");
      out.write("\t\t                console.error(\"Error:\", error);\r\n");
      out.write("\t\t                alert(\"파일 삭제 중 오류가 발생했습니다.\");\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 댓글 목록 새로고침 함수\r\n");
      out.write("\t    function refreshCommentList() {\r\n");
      out.write("\t\t\tconst testId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.testId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t        $.ajax({\r\n");
      out.write("\t            type: \"GET\",\r\n");
      out.write("\t            url: \"getCommentList.do\",\r\n");
      out.write("\t            data: { testId: testId },\r\n");
      out.write("\t            dataType: \"json\",\r\n");
      out.write("\t            success: function(commentList) {\r\n");
      out.write("\t                let html = '';\r\n");
      out.write("\t                \r\n");
      out.write("\t                if(commentList.length === 0) {\r\n");
      out.write("\t                    html = '<p class=\"text-center\">등록된 댓글이 없습니다.</p>';\r\n");
      out.write("\t                } else {\r\n");
      out.write("\t                    for(let i = 0; i < commentList.length; i++) {\r\n");
      out.write("\t                        let comment = commentList[i];\r\n");
      out.write("\t                        html += '<div class=\"card mb-2\">';\r\n");
      out.write("\t                        html += '  <div class=\"card-body\">';\r\n");
      out.write("\t                        html += '    <div class=\"d-flex justify-content-between\">';\r\n");
      out.write("\t                        html += '      <h5 class=\"card-title\">' + comment.commentName + '</h5>';\r\n");
      out.write("\t                        html += '      <small class=\"text-muted\">' + comment.commentDate + '</small>';\r\n");
      out.write("\t                        html += '    </div>';\r\n");
      out.write("\t                        html += '    <p class=\"card-text\">' + comment.commentContent + '</p>';\r\n");
      out.write("\t                        html += '    <div class=\"text-end\">';\r\n");
      out.write("\t                        html += '      <button type=\"button\" class=\"btn btn-sm btn-outline-primary btn-edit-comment\" data-comment-id=\"' + comment.commentId + '\">수정</button>';\r\n");
      out.write("\t                        html += '      <button type=\"button\" class=\"btn btn-sm btn-outline-danger btn-delete-comment\" data-comment-id=\"' + comment.commentId + '\">삭제</button>';\r\n");
      out.write("\t                        html += '    </div>';\r\n");
      out.write("\t                        html += '  </div>';\r\n");
      out.write("\t                        html += '</div>';\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                }\r\n");
      out.write("\t                $('#commentList').html(html); // HTML 삽입\r\n");
      out.write("\t            },\r\n");
      out.write("\t            error: function(error) {\r\n");
      out.write("\t                console.error(\"Error:\", error);\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    // 댓글 등록\r\n");
      out.write("\t    $('#btn_comment_submit').on('click', function () {\r\n");
      out.write("\t        const writer = $('#commentName').val();\r\n");
      out.write("\t        const content = $('#commentContent').val();\r\n");
      out.write("\t        \r\n");
      out.write("\t        if(!writer.trim()) {\r\n");
      out.write("\t            alert(\"작성자를 입력하세요.\");\r\n");
      out.write("\t            return;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t        if(!content.trim()) {\r\n");
      out.write("\t            alert(\"댓글 내용을 입력하세요.\");\r\n");
      out.write("\t            return;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t        if(confirm(\"정말 등록하시겠습니까?\")) {\r\n");
      out.write("\t\t        $.ajax({\r\n");
      out.write("\t\t            type: \"POST\",\r\n");
      out.write("\t\t            url: \"insertComment.do\",\r\n");
      out.write("\t\t            data: $('#commentForm').serialize(),\r\n");
      out.write("\t\t            success: function(response) {\r\n");
      out.write("\t\t                if(response === 'success') {\r\n");
      out.write("\t\t                    alert(\"댓글이 등록되었습니다.\");\r\n");
      out.write("\t\t                    $('#commentName').val('');\r\n");
      out.write("\t\t                    $('#commentContent').val('');\r\n");
      out.write("\t\t                    refreshCommentList();\r\n");
      out.write("\t\t                } else {\r\n");
      out.write("\t\t                    alert(\"댓글 등록에 실패했습니다.\");\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t            error: function(error) {\r\n");
      out.write("\t\t                console.error(\"Error:\", error);\r\n");
      out.write("\t\t                alert(\"댓글 등록 중 오류가 발생했습니다.\");\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    // 댓글 수정\r\n");
      out.write("\t    $(document).on('click', '.btn-edit-comment', function() {\r\n");
      out.write("\t        const commentId = $(this).data('comment-id');\r\n");
      out.write("\t        const commentText = $(this).closest('.card-body').find('.card-text').text();\r\n");
      out.write("\t        \r\n");
      out.write("\t        const newContent = prompt(\"댓글을 수정해주세요:\", commentText);\r\n");
      out.write("\t        \r\n");
      out.write("\t        if(newContent !== null && newContent.trim() !== '') {\r\n");
      out.write("\t            $.ajax({\r\n");
      out.write("\t                type: \"POST\",\r\n");
      out.write("\t                url: \"updateComment.do\",\r\n");
      out.write("\t                data: {\r\n");
      out.write("\t                    commentId: commentId,\r\n");
      out.write("\t                    commentContent: newContent\r\n");
      out.write("\t                },\r\n");
      out.write("\t                success: function(response) {\r\n");
      out.write("\t                    if(response === 'success') {\r\n");
      out.write("\t                        alert(\"댓글이 수정되었습니다.\");\r\n");
      out.write("\t                        refreshCommentList();\r\n");
      out.write("\t                    } else {\r\n");
      out.write("\t                        alert(\"댓글 수정에 실패했습니다.\");\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                },\r\n");
      out.write("\t                error: function(error) {\r\n");
      out.write("\t                    console.error(\"Error:\", error);\r\n");
      out.write("\t                    alert(\"댓글 수정 중 오류가 발생했습니다.\");\r\n");
      out.write("\t                }\r\n");
      out.write("\t            });\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    // 댓글 삭제\r\n");
      out.write("\t    $(document).on('click', '.btn-delete-comment', function() {\r\n");
      out.write("\t        const commentId = $(this).data('comment-id');\r\n");
      out.write("\t        \r\n");
      out.write("\t        if(confirm(\"정말 이 댓글을 삭제하시겠습니까?\")) {\r\n");
      out.write("\t            $.ajax({\r\n");
      out.write("\t                type: \"POST\",\r\n");
      out.write("\t                url: \"deleteComment.do\",\r\n");
      out.write("\t                data: { commentId: commentId },\r\n");
      out.write("\t                success: function(response) {\r\n");
      out.write("\t                    if(response === 'success') {\r\n");
      out.write("\t                        alert(\"댓글이 삭제되었습니다.\");\r\n");
      out.write("\t                        refreshCommentList();\r\n");
      out.write("\t                    } else {\r\n");
      out.write("\t                        alert(\"댓글 삭제에 실패했습니다.\");\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                },\r\n");
      out.write("\t                error: function(error) {\r\n");
      out.write("\t                    console.error(\"Error:\", error);\r\n");
      out.write("\t                    alert(\"댓글 삭제 중 오류가 발생했습니다.\");\r\n");
      out.write("\t                }\r\n");
      out.write("\t            });\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/mainDetail.jsp(44,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty vo.fileName}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                        <tr>\r\n");
        out.write("                            <th>다운로드</th>\r\n");
        out.write("                            <td>\r\n");
        out.write("                                <a href=\"fileDownload.do?fileName=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" class=\"btn btn-link\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</a>\r\n");
        out.write("                                <button id=\"filedelete\" type=\"button\" class=\"btn btn-danger btn-sm float-end\">파일삭제</button>\r\n");
        out.write("                            </td>\r\n");
        out.write("                        </tr>\r\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t            ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t            ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t        ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/jsp/mainDetail.jsp(78,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty commentList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t                <p class=\"text-center\">등록된 댓글이 없습니다.</p>\r\n");
        out.write("\t\t            ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t                ");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t            ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /WEB-INF/jsp/mainDetail.jsp(82,18) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/mainDetail.jsp(82,18) '${commentList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${commentList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/mainDetail.jsp(82,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("comment");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t                    <div class=\"card mb-2\">\r\n");
          out.write("\t\t                        <div class=\"card-body\">\r\n");
          out.write("\t\t                            <div class=\"d-flex justify-content-between\">\r\n");
          out.write("\t\t                                <h5 class=\"card-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h5>\r\n");
          out.write("\t\t                                <small class=\"text-muted\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</small>\r\n");
          out.write("\t\t                            </div>\r\n");
          out.write("\t\t                            <p class=\"card-text\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t                            <div class=\"text-end\">\r\n");
          out.write("\t\t                                <button type=\"button\" class=\"btn btn-sm btn-outline-primary btn-edit-comment\" data-comment-id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">수정</button>\r\n");
          out.write("\t\t                                <button type=\"button\" class=\"btn btn-sm btn-outline-danger btn-delete-comment\" data-comment-id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">삭제</button>\r\n");
          out.write("\t\t                            </div>\r\n");
          out.write("\t\t                        </div>\r\n");
          out.write("\t\t                    </div>\r\n");
          out.write("\t\t                ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
